version: '2'

services:
  web:
    image: renevanderark/chatbot-builder-web
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./files:/files
  nlp:
    image: renevanderark/chatbot-builder-nlp
  sample_webhook:
    image: renevanderark/chatbot-builder-sample-webhook
    env_file: .env
    ports:
      - "5002:5002"
    volumes:
      - ./files:/files
