const ActionTypes = {
    RECEIVE_DIALOGS: "RECEIVE_DIALOGS",
    SET_USERNAME: "SET_USERNAME",
    RECEIVE_CHAT_RESPONSE: "RECEIVE_CHAT_RESPONSE",
    CLEAR_CHAT: "CLEAR_CHAT",
    SET_GREETING: "SET_GREETING"
};

export default ActionTypes;